### ISSUE TITLE
Update to python 3.8?

### ISSUE THREAD

**Issue by bsteiner-dandy** [xadrianzetx/coral-deeplab#23]
Would it be possible to update this for Python 3.8? Google Colab has stopped supporting 3.7 since it is end of life in a few months

**Comment by xadrianzetx** [comment]
Python is pinned due to the issues with unmarshalling pretrained keras models in newer versions (loosely described [here](https://stackoverflow.com/a/73441916)). Fixing this issue would require re-training all models and possibly switching serialization format, which I don't really have a capacity to do now.

However, as you pointed out, Python 3.7 eol is close, so I'd be willing to temporarily drop pre-trained models feature and unpin Python version. This way users interested in training models from scratch or just using precompiled tflite could do so without unnecessary constraints. If you'd be interested in contributing these changes, I'd be happy to review the PR.
